@startuml
' autoactivate on

actor user

System -> WormNavApp : onStart
participant TrackView
activate WormNavApp
  create TrackModel
  WormNavApp -> TrackModel : load from property
return

System -> WormNavApp : getInitialView
activate WormNavApp
  create TrackView
  WormNavApp -> TrackView
  activate TrackView
    TrackView -> Trace : reset
  deactivate TrackView
deactivate WormNavApp

System -> TrackView : onLayout
activate TrackView
  TrackView -> Transform : setPixelDimensions
deactivate TrackView

System -> TrackView : onShow

System -> WormNavApp : onPosition
activate WormNavApp
  WormNavApp -> Trace : new_pos
  Trace -> Transform : latlon_to_xy
  alt one lap
    create LapView
    WormNavApp -> LapView
  end
  WormNavApp -> TrackView : onPosition
  activate TrackView
    TrackView -> Transform : setPosition
    TrackView -> System : requestUpdate
  deactivate TrackView
return

System -> TrackView : onUpdate
activate TrackView
  alt track was changed
    TrackView -> Transform : onTrackChange
    activate Transform
      Transform -> TrackModel : get data
    deactivate Transform
  end
  TrackView -> TrackModel : get data
  TrackView -> Trace : get data
  TrackView -> Transform : calculate pixels
  TrackView -> TrackView : draw on DC
return



@enduml